### ISSUE TITLE
need test PreCrowdSall ( Payable )

### ISSUE THREAD

**Issue by liderako** [liderako/Crystals-Love#15]

**Comment by rmalkevy** [comment]
- ефір приходить під час граудсейла
- ефір не приходить після дедлайна

**Comment by rmalkevy** [comment]
- Можна зробити покупку на 1 wei
- без setAuthorizeUser payable не працює

**Comment by rmalkevy** [comment]
не пропускає більше ефіру ніж є токенів. Наприклад є токенів на 1 ефір, а тому 2 ефіра зайти не може.

**Comment by rmalkevy** [comment]
при досягненні цілі зі збору ефіру залишається 0 токенів

**Comment by rmalkevy** [comment]
При досягненні цілі, ефір уже не приймається
